### ISSUE TITLE
ConsentRegistration.status moet van type int zijn ipv string (niet consequent met de rest)

### ISSUE THREAD

**Issue by andremussche** [stichtingsem/ecosystem#145]
In de response van een consent update heeft het status veld het type "string" terwijl verder overal type "int" gebruikt wordt:
```
 ConsentRegistration:
      type: object
      properties:
        status:
          type: string    <<<<<<
          description: 'See functional status codes within the Documentation.'
          example: 0
```
