### ISSUE TITLE
Exchange of groups in SIS API (stamgroep/stamklas vs. lesgroep/clustergroep)

### ISSUE THREAD

**Issue by niesink** [stichtingsem/ecosystem#24]
It is common for students, especially in the first years of their education, to take multiple subjects with the same group of students (in Dutch: stamgroep/stamklas).

Recently a difference of understanding came to light with regards to the groups that are exchanged in the SIS API. 

With the central question being: should the SIS API publish:
* **option A**: where possible, a single group with all the students, subjects and teachers (i.e. de stamgroep/stamklas)
* **option B**: always a seperate group for each subject (i.e. de lesgroepen/clustergroepen)

_Example A:_
```
group:
  name: H4a
  students: 11, 22, 33
  teachers: N.ederlands, E.ngels, W.iskunde
  subjects: ne, en, wi

group:
  name: H4a.ec
  students: 11, 22
  teachers: E.conomie
  subjects: ec

group:
  name: H4a.bi
  students: 22, 33
  teachers: B.iologie
  subjects: bi
```
 

_Example B:_
```
group:
  name: H4a.ne
  students: 11, 22, 33
  teachers: N.ederlands
  subjects: ne

group:
  name: H4a.en
  students: 11, 22, 33
  teachers: E.ngels
  subjects: en

group:
  name: H4a.wi
  students: 11, 22, 33
  teachers: W.iskunde
  subjects: wi

group:
  name: H4a.ec
  students: 11, 22
  teachers: E.conomie
  subjects: ec

group:
  name: H4a.bi
  students: 22, 33
  teachers: B.iologie
  subjects: bi
  ```
